### ISSUE TITLE
send region to shell

### ISSUE THREAD

**Issue by mankoff** [ieure/shell-here#1]
I've been using `shell` but would like to switch to `shell-here`. I have [a function that sends the current region to the `*shell*` buffer](https://stackoverflow.com/questions/6286579/emacs-shell-mode-how-to-send-region-to-shell), but am having trouble adapting it to `shell-here`. Can you suggest how to send the current line and/or region to the correct shell when using `shell-here`?

**Comment by ieure** [comment]
[This code down at the bottom of `shell-here`](https://github.com/ieure/shell-here/blob/master/shell-here.el#L145-L157) is what you need. It's used internally to change directories, but could be adapted trivially to send any input. You'd just want to replace the `insert` call to put your commands into the buffer, and remove the `shell-cd` — that's used to ensure that shell-mode's directory tracking is in sync with the shell's.

**Comment by mankoff** [comment]
I solved this by using shell-current-directory (`(use-package shell-current-directory)`) and the code below:

``` elisp
(defun kdm/sh-send-line-or-region () 
(interactive)
(if (use-region-p) 
  (append-to-buffer (get-buffer (directory-shell-buffer-name)) (mark)(point))
  (let (p1 p2)
    (setq p1 (line-beginning-position))
    (setq p2 (line-end-position))
    (append-to-buffer (get-buffer (directory-shell-buffer-name)) p1 p2)
  ))
  (let (b)
    (setq b (get-buffer (current-buffer)))
    (switch-to-buffer-other-window (get-buffer (directory-shell-buffer-name)))
    (execute-kbd-macro "\C-m")
    (switch-to-buffer-other-window b)
    )
  )
```
